### PR TITLE
Switched to std::isnan in mbinfo

### PR DESCRIPTION
**Pull request by berkowski**
mbinfo.cc is failing for me on Ubuntu 16.04 LTS with gcc 5.4.0: 

> mbinfo.cc: In function ‘int main(int, char**)’:
> mbinfo.cc:2159:24: error: ‘isnan’ was not declared in this scope
>          if (isnan(sigma))
>                         ^
> mbinfo.cc:2159:24: note: suggested alternative:
> In file included from /usr/include/c++/5/random:38:0,
>                  from /usr/include/c++/5/bits/stl_algo.h:66,
>                  from /usr/include/c++/5/algorithm:62,
>                  from mbinfo.cc:36:
> /usr/include/c++/5/cmath:641:5: note:   ‘std::isnan’
>      isnan(_Tp __x)

This build failure seems to have been introduced in 98b32be410 and I think what's going on is summarized in https://stackoverflow.com/a/39133379 where `<algorithm>` is pulling in `<cmath>` which undefines isnan in `<math.h>` for this version of gcc.  The last 'release' I'm able to build is 5.7.6beta21.

I've been able to reproduce build errors on travis:  
- Xenial w/ gcc 5.4.0 fails:  https://travis-ci.com/berkowski/MB-System/jobs/275150675.  
- Xenial w/ clang 7.0.0 passes: https://travis-ci.com/berkowski/MB-System/jobs/275150674
- Bionic w/ gcc 7.4.0 passes: https://travis-ci.com/berkowski/MB-System/jobs/275150673 

In the PR I've removed the math.h include and switched isnan to std::isnan as provided by `<cmath>`.

I can also share my travis config if the project is interested.  Right now I think you're only testing on disco?  I was able to get builds w/ gcc and clang on xenial and bionic with GMT 6.0.0, though it requries building GMT from source.  It might help catch more build issues for slightly older systems.

### CODE REVIEW

**Comment by schwehr** [comment]
Thanks for the patch!

It looks like I got one in src/utilities/mbkongsbergpreprocess.cc with 72cf01ef6, but I've also missed some in deprecated/mbstripnan.cc

**Comment by berkowski** [comment]
I can rebase/squish these two commits and look for more cases if you like.  Try to knock them out in a single PR.

**Comment by schwehr** [comment]
Additional travis builds would be great, but I'd rather not go back to xenial / 16.04LTS.  We might as well add bionic / 18.04LTS if it works.  I'd love to see Eoan/19.10 and (if it works yet) focal /20.04LTS.  I see there is a docker instance for focal... https://hub.docker.com/_/ubuntu/

We could also really use a clang build (on the newest possible platform) if possible to get at least one other compiler going.

+1 if we can also get docker instances that have been prebuilt to avoid the massive install / update step that I currently have going.  That would drastically reduce the time to run the whole test cycle. 
 @cdsferreira was looking into this.  I'm not sure how much progress he has made.

**Comment by schwehr** [comment]
It's up to you if you want to do a single PR or just make a new one.   I see just this:

```bash
grep isnan */*/*.cc | egrep -v 'std::|mbinfo.cc'
src/deprecated/mbstripnan.cc:#if defined(_WIN32) && !defined(isnan)
src/deprecated/mbstripnan.cc:#define isnan(x) _isnan(x)
src/deprecated/mbstripnan.cc:		if (isnan(n.lon) || isnan(n.lat) || isnan(n.height)) {
```

**Comment by berkowski** [comment]
`mbstripnan.cc` only includes `<math.h>` and so shouldn't have the same problem that `mbinfo.cc` has, and since it's already marked deprecated I'd rather just leave it as is if it's compiling.  All the other files I see using isnan are part of the `mbtrnav` project which I won't touch.

I'll squash these two commits and repush and call it good for now.

I don't mind looking at creating more docker instances for testing but don't want to step on someone else's toes if they're already working on it.  Looks like #327 and #807 both brush up against the desired issue.  If the desire is strong enough I would suggest creating a new issue specifically for docker images to be used with travis that list the desired combinations of OS/compiler/gmt

**Comment by schwehr** [comment]
@berkowski If you are up for docker configs, please go for it.
