### ISSUE TITLE
configuere error on linux (ubuntu) can't find tirpc/rpc/types.h

### ISSUE THREAD

**Issue by epifanio** [dwcaress/MB-System#1262]
**Describe the bug**

The latest stable release 5.7.8 doesn't build on most linux OS - I tried both ubuntu and debian distro
Here the logs for ubutnu 21.04

**To Reproduce**
Provide information sufficient to reproduce the behavior:

```
mkdir -p /opt/mb && cd /opt/mb && wget https://github.com/dwcaress/MB-System/archive/5.7.8.tar.gz && \
    tar -zxvf 5.7.8.tar.gz && \
    cd MB-System-5.7.8 && \
    sh autogen.sh && \
    ./configure --disable-mbtools --with-proj-include=/usr/include 
```

**Expected behavior**
No configure errors

configure log:

```
checking tirpc/rpc/types.h presence... no
checking for tirpc/rpc/types.h... no
configure: error: Required header <rpc/types.h> not found, check include path and installed development packages
```
Note: the file is here
/usr/include/tirpc/rpc/types.h 

**Computing context (please complete the following information):**
 - OS: Ubuntu 21.04
 - MB-System version  5.7.8
 - GMT version  6.3.0

**Additional context**
Note: mb system v 5.7.5 builds without errors on the same system - the configure error mentioned in the bug report applies also to 5.7.6 release and to the Github master branch.

**Comment by epifanio** [comment]
This problem persist also with the latest ubuntu release - 22.04
can anyone help in identifying the missing dependency? 

the following:

```
apt-file search rpc/types.h
```
returns:
```
libntirpc-dev: /usr/include/ntirpc/rpc/types.h
libtirpc-dev: /usr/include/tirpc/rpc/types.h
...
```

I have installed both, `libtirpc-dev` and `libntirpc-dev` but the error persists :

```
checking for rpc/rpc.h... no
checking for tirpc/rpc/rpc.h... no
checking for rpc/types.h... no
checking for tirpc/rpc/types.h... no
configure: error: Required header <rpc/types.h> not found, check include path and installed development packages
```

I am using " https://github.com/dwcaress/MB-System/archive/5.7.5.tar.gz" as it is the latest release that I know that is compatible with the MB-System PDAL plug-in - but  I tried to build also with `v5.7.6/7/8` but I got the same configure error.


@dwcaress  @schwehr  -  Thanks for any advice.

**Comment by dwcaress** [comment]
Please try the beta release: 
https://github.com/dwcaress/MB-System/releases/tag/5.7.9beta29

I am able to build this on Ubuntu 20.04.

Cheers,
Dave

> On May 9, 2022, at 12:46 AM, epifanio ***@***.***> wrote:
> 
> 
> This problem persist also with the latest ubuntu release - 22.04
> can anyone help in identifying the missing dependency?
> 
> the following:
> 
> apt-file search rpc/types.h
> 
> returns:
> 
> libntirpc-dev: /usr/include/ntirpc/rpc/types.h
> libtirpc-dev: /usr/include/tirpc/rpc/types.h
> ...
> 
> I have installed both, libtirpc-dev and libntirpc-dev but the error persists :
> 
> checking for rpc/rpc.h... no
> checking for tirpc/rpc/rpc.h... no
> checking for rpc/types.h... no
> checking for tirpc/rpc/types.h... no
> configure: error: Required header <rpc/types.h> not found, check include path and installed development packages
> 
> I am using " https://github.com/dwcaress/MB-System/archive/5.7.5.tar.gz" as it is the latest release that I know that is compatible with the MB-System PDAL plug-in - but I tried to build also with v5.7.6/7/8 but I got the same configure error.
> 
> @dwcaress @schwehr - Thanks for any advice.
> 
> —
> Reply to this email directly, view it on GitHub, or unsubscribe.
> You are receiving this because you were mentioned.
> 

----------------------------------------------------
David W. Caress
Principal Engineer
Seafloor Mapping Lab

Monterey Bay Aquarium Research Institute
7700 Sandholdt Road
Moss Landing, CA 95039

***@***.***
http://www.mbari.org/~caress/

Phone: 831-775-1775

**Comment by tomoreilly** [comment]
libr7kr and libmframe are in MB-SYSTEM/src/mbtrn and src/mbtrnframe, respectively.
They are related to TRN.

Not sure if it's related, but Dave just committed some build system changes to a beta release that updated some build paths for compatibility with OSX Monterey.

Are you working from a very recent (<24h) tree?

- kent

**Comment by tomoreilly** [comment]
Thanks Kent. 
I'm working in the feature-newgui branch which I haven't pulled recently, so don't expect to see the recent changes you refer to. 

Tom 


-------------------------------------------------- 
Thomas C. O'Reilly 
Monterey Bay Aquarium Research Institute 
7700 Sandholdt Road 
Moss Landing, California 95039-9644 
831-775-1766 (voice) 
831-775-1620 (FAX) 
***@***.*** (email) 
http://www.mbari.org (World-wide Web) 

"The machine does not isolate us from the great mysteries 
of nature, but plunges us more deeply into them." 

- ANTOINE DE SAINT-EXUPERY 
"Wind, Sand, and Stars" (1939)

**Comment by tomoreilly** [comment]
Ok, are you using cmake or autotools to build?

**Comment by tomoreilly** [comment]
Hi Kent, 

Are r7kr and mframe libraries built from source in src/mbtrn? Or are they third-party? 

Thanks 
Tom 

-------------------------------------------------- 
Thomas C. O'Reilly 
Monterey Bay Aquarium Research Institute 
7700 Sandholdt Road 
Moss Landing, California 95039-9644 
831-775-1766 (voice) 
831-775-1620 (FAX) 
***@***.*** (email) 
http://www.mbari.org (World-wide Web) 

"The machine does not isolate us from the great mysteries 
of nature, but plunges us more deeply into them." 

- ANTOINE DE SAINT-EXUPERY 
"Wind, Sand, and Stars" (1939)

**Comment by tomoreilly** [comment]
I see that MB-System/CMakeLists.txt takes option -DbuildTrn=1, which I didn't use for the build that flagged those missing libraries. 
Now when I specify '-DbuildTrn=1' to cmake I get: 

CMake Error at CMakeLists.txt:298 (add_subdirectory): 
The source directory 

/home/oreilly/projects/mb-system/MB-System/src/mbtrn 

does not contain a CMakeLists.txt file. 

So maybe my feature-newgui branch is far out of date. 

When I try to pull on that branch git fails - says I need to commit over 100 .ps files in src/ps. 
Not sure what modified them - are they auto-generated? If so, why are they source-maintained? 

Thanks 
Tom 
-------------------------------------------------- 
Thomas C. O'Reilly 
Monterey Bay Aquarium Research Institute 
7700 Sandholdt Road 
Moss Landing, California 95039-9644 
831-775-1766 (voice) 
831-775-1620 (FAX) 
***@***.*** (email) 
http://www.mbari.org (World-wide Web) 

"The machine does not isolate us from the great mysteries 
of nature, but plunges us more deeply into them." 

- ANTOINE DE SAINT-EXUPERY 
"Wind, Sand, and Stars" (1939)

**Comment by tomoreilly** [comment]
I haven't tried a cmake build on ubuntu.
Not too long ago, I merge changes from feature/new-gui into trndev, and may have changed a thing or two in the cmake TRN build that seemed broken.

You could try building the trndev branch as a diagnostic exercise.

Kent

**Comment by tomoreilly** [comment]
Somehow got myself into a bad git place with these 'modified' src/ps files. git status shows them all as 'modified' yet I cannot commit those changes - get 'fatal: cannot do a partial commit during a merge' when I try to commit any of them. Where do those .ps files come from? 

Thanks 
Tom 


-------------------------------------------------- 
Thomas C. O'Reilly 
Monterey Bay Aquarium Research Institute 
7700 Sandholdt Road 
Moss Landing, California 95039-9644 
831-775-1766 (voice) 
831-775-1620 (FAX) 
***@***.*** (email) 
http://www.mbari.org (World-wide Web) 

"The machine does not isolate us from the great mysteries 
of nature, but plunges us more deeply into them." 

- ANTOINE DE SAINT-EXUPERY 
"Wind, Sand, and Stars" (1939)

**Comment by tomoreilly** [comment]
Got myself out of that particular git hell by adding the '-i' flag to 'git commit' 


-------------------------------------------------- 
Thomas C. O'Reilly 
Monterey Bay Aquarium Research Institute 
7700 Sandholdt Road 
Moss Landing, California 95039-9644 
831-775-1766 (voice) 
831-775-1620 (FAX) 
***@***.*** (email) 
http://www.mbari.org (World-wide Web) 

"The machine does not isolate us from the great mysteries 
of nature, but plunges us more deeply into them." 

- ANTOINE DE SAINT-EXUPERY 
"Wind, Sand, and Stars" (1939)

**Comment by tomoreilly** [comment]
Hi Kent, 

Do you have a set of CMakeFileLists.txt files in some branch that work under MacOS? I'm thinking that the cmake structure I'm using might be properly meshing with what you are using for trn stuff. In particular MB-System/CMakeFileLists.txt is expecting to find src/mbtrn/CMakeFileLists.txt, but that file doesn't exist in master, feature-newgui, or trndev branches. 

Thanks 
Tom 

-------------------------------------------------- 
Thomas C. O'Reilly 
Monterey Bay Aquarium Research Institute 
7700 Sandholdt Road 
Moss Landing, California 95039-9644 
831-775-1766 (voice) 
831-775-1620 (FAX) 
***@***.*** (email) 
http://www.mbari.org (World-wide Web) 

"The machine does not isolate us from the great mysteries 
of nature, but plunges us more deeply into them." 

- ANTOINE DE SAINT-EXUPERY 
"Wind, Sand, and Stars" (1939)

**Comment by tomoreilly** [comment]
When I say " a set of CMakeFileLists.txt files in some branch that work under MacOS", I mean CMakeFileLists.txt for the trn software. 

Thanks 
Tom 

-------------------------------------------------- 
Thomas C. O'Reilly 
Monterey Bay Aquarium Research Institute 
7700 Sandholdt Road 
Moss Landing, California 95039-9644 
831-775-1766 (voice) 
831-775-1620 (FAX) 
***@***.*** (email) 
http://www.mbari.org (World-wide Web) 

"The machine does not isolate us from the great mysteries 
of nature, but plunges us more deeply into them." 

- ANTOINE DE SAINT-EXUPERY 
"Wind, Sand, and Stars" (1939)

**Comment by tomoreilly** [comment]
The cmake configuration for TRN evolved from an immediate need to integrate with Sentry, and it hasn't caught up with the rest of MB-System; sorry about that.
The short answer is that no CMakeFileLists.txt exists in trndev branch in TRN directories (mbtrn, mbtrnav, mbtrnframe, mbtrnutils).

There is a CMakeLists.txt in mbtrnav that is used to build TRN for sentry. It requires mframe (in mbtrnframe).
Really, it was made so that the libtrnav and mframe repos (mbtrnav and mbtrnframe mirror these repos) can be integrated into Sentry code, which uses cmake.

So the cmake build is not tightly integrated with MB-System, and doesn't include the MB-System-specific libs and apps (mbtrn, mbtrnutils).

If you don't need TRN and it's vexing the build, I think it can be switched out using configure; I thought it's omitted by default, and these flags enable it.

--enable-mbtrn          build mbtrn tools
--enable-mbtnav         build mbtnav tools

but maybe --disable-mbtrn --disable-mbtnav may be used?

**Comment by epifanio** [comment]
> Please try the beta release: https://github.com/dwcaress/MB-System/releases/tag/5.7.9beta29 I am able to build this on Ubuntu 20.04. Cheers, Dave

@dwcaress 

I tried witrh the latest beta:

```
➜  build git:(main) ✗ ccmake ..                                                                             


➜  build git:(main) ✗ make     
Consolidate compiler generated dependencies of target mbgsf
[  3%] Built target mbgsf
[  4%] Building C object src/mbaux/CMakeFiles/mbaux.dir/mb_cheb.c.o
In file included from /home/epinux/dev/PHD/HBC-browser/docker/MB-System-5.7.9beta35/src/mbio/mb_io.h:27,
                 from /home/epinux/dev/PHD/HBC-browser/docker/MB-System-5.7.9beta35/src/mbaux/mb_aux.h:36,
                 from /home/epinux/dev/PHD/HBC-browser/docker/MB-System-5.7.9beta35/src/mbaux/mb_cheb.c:61:
/home/epinux/dev/PHD/HBC-browser/docker/MB-System-5.7.9beta35/src/mbio/mb_define.h:42:12: fatal error: rpc/rpc.h: No such file or directory
   42 | #  include <rpc/rpc.h>
      |            ^~~~~~~~~~~
compilation terminated.
make[2]: *** [src/mbaux/CMakeFiles/mbaux.dir/build.make:76: src/mbaux/CMakeFiles/mbaux.dir/mb_cheb.c.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:418: src/mbaux/CMakeFiles/mbaux.dir/all] Error 2
make: *** [Makefile:136: all] Error 2
```

The build issue is with Ubuntu >20  - I am now trying with:  22.04

MB-System-5.7 builds fine on ubuntu 22.04

**Comment by dwcaress** [comment]
If you have installed libtirpc-dev and libntirpc-dev on Ubuntu 22.04, where are the rpc.h types.h and xdr.h header files installed? If these headers are inside either /usr/include/rpc/ or /usr/include/tirpc/rpc/ then the existing configure script should find them.

**Comment by epifanio** [comment]
git master builds fine, the version I am trying to build 5.7.5 (I tried up to 5.7.8) doesn't build - it is asking for 

```
Build does not require -DSUN CFLAG
Not WIN32 system
checking for rpc/rpc.h... no
checking for tirpc/rpc/rpc.h... no
checking for rpc/types.h... no
checking for tirpc/rpc/types.h... no
configure: error: Required header <rpc/types.h> not found, check include path and installed development packages
```

but the files are there, this the output of :

```
RUN ls /usr/include/tirpc/
RUN ls /usr/include/tirpc/rpc
```
just before the MB-System `5.7.8` build, which returns the following output:


```
Step 12/22 : RUN ls /usr/include/tirpc/
 ---> Running in cbc7319085fb
netconfig.h
rpc
rpcsvc
Removing intermediate container cbc7319085fb
 ---> 1c98bb74a347
Step 13/22 : RUN ls /usr/include/tirpc/rpc
 ---> Running in 25b4a819acd2
auth.h
auth_des.h
auth_gss.h
auth_unix.h
clnt.h
clnt_soc.h
clnt_stat.h
des.h
des_crypt.h
key_prot.h
nettype.h
pmap_clnt.h
pmap_prot.h
pmap_rmt.h
raw.h
rpc.h
rpc_com.h
rpc_msg.h
rpcb_clnt.h
rpcb_prot.h
rpcb_prot.x
rpcent.h
rpcsec_gss.h
svc.h
svc_auth.h
svc_auth_gss.h
svc_dg.h
svc_mt.h
svc_soc.h
types.h
xdr.h
Removing intermediate container 25b4a819acd2
```

The problem (with me) is that I need a specific MB-System Version (5.7.5) as it "seems" to be the latest version compatible with the [MB-System-PDAL driver](https://pdal.io/stages/readers.mbio.html)  

I do not know what will be easier/useful:
1)  fix the MB-System v5.7.5 build on ubuntu 22.04 
2)  try to install and debug the MB-System PDAL driver using MB-System master

I personally think opton 1 should be easier, but option 2 more useful for the community.

**Comment by epifanio** [comment]
More debug .. which seems to be related.
I decided to give one morte try at buildinmg MB-System [git:master] - which builds without errors on ubuntu 22.04
and then build PDAL [git:master] enabling the MB.io drivers.

The build ends wit the same error given by MB-System v5.7.5/ on ubuntu 22.04 which is the following:

```
[ 54%] Building CXX object test/unit/CMakeFiles/pdal_point_view_test.dir/PointViewTest.cpp.o
[ 55%] Building CXX object test/unit/CMakeFiles/pdal_pipeline_writer_test.dir/PipelineWriterTest.cpp.o
[ 56%] Building CXX object test/unit/CMakeFiles/pdal_deflate_test.dir/DeflateTest.cpp.o
[ 56%] Building CXX object test/unit/CMakeFiles/pdal_zstd_test.dir/ZstdTest.cpp.o
[ 56%] Building CXX object test/unit/CMakeFiles/pdal_utils_test.dir/UtilsTest.cpp.o
In file included from /opt/pdal/PDAL/plugins/mbio/io/MbReader.hpp:46,
                 from /opt/pdal/PDAL/plugins/mbio/io/MbReader.cpp:35:
/usr/local/include/mb_define.h:42:12: fatal error: rpc/rpc.h: No such file or directory
   42 | #  include <rpc/rpc.h>
      |            ^~~~~~~~~~~
compilation terminated.
make[2]: *** [plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/build.make:76: plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/io/MbReader.cpp.o] Error 1
make[1]: *** [CMakeFiles/Makefile2:699: plugins/mbio/CMakeFiles/pdal_plugin_reader_mbio.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....
[ 56%] Building CXX object test/unit/CMakeFiles/pdal_eigen_test.dir/__/__/pdal/private/MathUtils.cpp.o
[ 56%] Linking CXX executable ../../bin/pdal_uuid_test
[ 57%] Linking CXX executable ../../bin/pdal_georeference_test
[ 57%] Linking CXX executable ../../bin/pdal_config_test
[ 57%] Linking CXX executable ../../bin/pdal_log_test
[ 58%] Linking CXX executable ../../bin/pdal_support_test
[ 58%] Linking CXX executable ../../bin/pdal_deflate_test
[ 58%] Linking CXX executable ../../bin/pdal_zstd_test
```

**Comment by tomoreilly** [comment]
Using cmake 

-------------------------------------------------- 
Thomas C. O'Reilly 
Monterey Bay Aquarium Research Institute 
7700 Sandholdt Road 
Moss Landing, California 95039-9644 
831-775-1766 (voice) 
831-775-1620 (FAX) 
***@***.*** (email) 
http://www.mbari.org (World-wide Web) 

"The machine does not isolate us from the great mysteries 
of nature, but plunges us more deeply into them." 

- ANTOINE DE SAINT-EXUPERY 
"Wind, Sand, and Stars" (1939)

**Comment by schwehr** [comment]
xdr support has left most libc implementations.  You may have installed the
rpc headers, but if you look in the autoconf logs, you will likely find
that you need to add just one of shared lib to the list of linked
libraries.  And make sure that it's finding the matching header files.
Having both around and getting some of one and some of another into one
build is likely going to lead to rough times.

**Comment by epifanio** [comment]
> Please try the beta release: https://github.com/dwcaress/MB-System/releases/tag/5.7.9beta29 I am able to build this on Ubuntu 20.04. Cheers, Dave


@dwcaress  - I am still struggling with this :( - My problem is that I am forced to use V5.7.5 on Ubuntu 22.04 - The reason is the need of using the PDAL driver for MB-System - I opened a ticket for it - is could someone look into it.
- https://github.com/PDAL/PDAL/issues/3791#issuecomment-1488610004
- https://github.com/dwcaress/MB-System/issues/1354

On those open tickets I also added a docker environment to replicate the issue, which could probably help to debug "someone with PDAL / MB-System knowledge"  @abellgithub <3 ?

I can't switch back to an older Ubuntu, as all the libraries I rely on are for 22.04, which is the Latest and greatest :) MB-System builds just fine.  The problem is that the PDAL driver for MB-System fails to initialize with MB-System Version greater than 5.7.5.

I have checked with @hobu from the PDAL dev team, and they confirmed the MBIO driver did not change; there is no error when building them with a newer MB-System version - but they silently fail to initialize. 

so, I've been left with two options:
- be able to build 5.7.5 on ubuntu 22.04
- have the latest MB-System working with PDAL MBIO driver
In both cases, I failed in finding a fix :(
